In [1]:
import numpy as np

## Numpy Array 생성

In [6]:
test_array = np.array([1,4,5,8], np.float32)
test_array

array([1., 4., 5., 8.], dtype=float32)

In [5]:
type(test_array[3])

numpy.float64

In [7]:
# 다이내믹 타이핑
test_array = np.array([1,4,5, "8"], np.float32)
test_array

array([1., 4., 5., 8.], dtype=float32)

In [8]:
test_array.shape

(4,)

In [10]:
# 자료형 확인
test_array.dtype

dtype('float32')

# Shape Handling

In [12]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
np.array(test_matrix).shape

(2, 4)

In [15]:
np.array(test_matrix).reshape(8,).shape

(8,)

In [16]:
np.array(test_matrix).reshape(-1, 2).shape
# 전체 사이즈를 기반으로 갯수 산정 : -1

(4, 2)

In [17]:
a = np.array(test_matrix).reshape(2,2,2)
a.size

8

In [18]:
a.reshape(-1,4)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [20]:
a.shape

(2, 2, 2)

In [21]:
a.reshape(-1,)

array([1, 2, 3, 4, 1, 2, 5, 8])

## Flatten
다차원 array를 1차원으로 변환

In [22]:
test_matrix = [[[1,2,4,5], [1,2,4,5]], [[1,2,4,5],[5,6,7,8]]]
a = np.array(test_matrix).flatten()
a.shape

(16,)

# Indexing, Slicing

In [23]:
a = np.array([[1,2,4],[4.5,5,6]], int)

In [25]:
print(a)

[[1 2 4]
 [4 5 6]]


In [26]:
print(a[0,0]) # 이런형태의 인덱싱도 지원한다. == a[0][0]

1


In [28]:
print(a[0][0])

1


In [30]:
a[0,2] = 10
a

array([[ 1,  2, 10],
       [ 4,  5,  6]])

In [31]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],int)
a[:, 2:] # row 전체, col 2번부터

array([[ 3,  4,  5],
       [ 8,  9, 10]])

1 2 [3 4 5]

6 7 [8 9 10]

In [33]:
a[1:3] # 1row~ 3row의 전체, 2, 3은 없으니까 잘려나옴

array([[ 6,  7,  8,  9, 10]])

# Create Function

In [35]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [37]:
np.arange(0, 5, 0.5) # 시작, 끝 step

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [40]:
np.arange(30).reshape(-1,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## 특정 값으로 찬 배열

In [41]:
np.zeros(shape=(10,), dtype=np.int8)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [44]:
np.ones((2,5), int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [46]:
np.empty(shape=(10,), dtype=np.int8) # 메모리를 초기화 시키지 않음

array([  0,   0,   0,   0,   0,   0,   0, 112,  89,   7], dtype=int8)

In [48]:
# 같은 크기의 배열 반환하는 something_like
test_matrix = np.arange(30).reshape(-1,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

## identity
단위행렬(I) 생성

In [49]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

## eye
대각행렬, 1

In [51]:
np.eye(3)
np.eye(3,5,k=2) # k:스타팅 포인트

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## diag
대각 행렬의 값 추출

In [52]:
matrix = np.arange(30).reshape(5,6)
np.diag(matrix)

array([ 0,  7, 14, 21, 28])

## random sampling
분포에 따라 값을 추출함

In [54]:
np.random.uniform(0,1,10).reshape(2,5) # 균등분포

array([[0.12213168, 0.33404533, 0.30134464, 0.60900034, 0.65764163],
       [0.13759375, 0.41165594, 0.68381772, 0.50606411, 0.41347889]])

In [55]:
np.random.normal(0,1,10).reshape(2,5) # 정규분포(평균, 표준편차)

array([[-0.76303203, -1.44421979,  1.82069267,  0.78719547,  1.33026631],
       [ 2.88197661,  1.31291686,  0.16596896,  1.04215342, -0.94666143]])

# Operation

In [59]:
test_array = np.random.normal(0,1,10).reshape(2,5)
test_array

array([[ 0.26613644, -0.375172  , -1.73189204,  0.31356966,  0.70598863],
       [-0.48060815, -1.3814484 ,  0.47926016,  0.89958927,  1.63380443]])

In [63]:
test_array.sum(axis=1).shape # axis=(0,1) 이다.

(2,)

In [64]:
test_array.sum(axis=0).shape

(5,)

In [65]:
# 3차원에서
third = np.array([test_array, test_array, test_array])

In [66]:
third.shape

(3, 2, 5)

In [67]:
third.sum(axis=0).shape

(2, 5)

In [68]:
third.sum(axis=1).shape

(3, 5)

In [69]:
third.sum(axis=2).shape

(3, 2)

## mean & std
평균과 표준편차

In [70]:
test_array.mean()

0.03292279972942604

In [72]:
test_array.mean(axis=1) # 특정 축만도 구할 수 있음

array([-0.16427386,  0.23011946])

In [73]:
test_array.std()

0.9820688070108893

In [74]:
test_array.std(axis=0)

array([0.37337229, 0.5031382 , 1.1055761 , 0.2930098 , 0.4639079 ])

# concatenate

In [83]:
a = np.array([[1],[2],[3]])
b = np.array([[1],[2],[3]])
a.shape

(3, 1)

In [80]:
c = np.vstack((a,b))
c.shape

(6, 1)

In [81]:
d = np.hstack((a,b))
d.shape

(3, 2)

In [84]:
# 합치는걸 좀 자유롭게
np.concatenate((a,b), axis=1)

array([[1, 1],
       [2, 2],
       [3, 3]])

In [87]:
a = np.array([[1,2],[3,4]])
b = np.array([[5, 6]])

np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

# Array Operatons
배열 간의 계산

In [89]:
a = np.array([[1,2,3],[4,5,6]])
a + a # 각 원소끼리 계산

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [90]:
a - a

array([[0, 0, 0],
       [0, 0, 0]])

In [94]:
a * a # 원소간 곱 계산 (element-wise) : shape이 같을 때 계산 가능

array([[ 1,  4,  9],
       [16, 25, 36]])

In [95]:
a = np.arange(1,7).reshape(2,3)
b = np.arange(1,7).reshape(3,2)

np.dot(a,b)

array([[22, 28],
       [49, 64]])

In [97]:
a.T # transpose행렬 구하기

array([[1, 4],
       [2, 5],
       [3, 6]])

## broadcasting
shape가 다를 때 연산을 자동으로 지원

In [100]:
a + 3 # 스칼라 3이 브로드캐스팅 되어 전체에 더해짐

array([[4, 5, 6],
       [7, 8, 9]])

In [102]:
a * 3 # 사칙연산이 다 가능. (%, ** 연산자도 가능)

array([[ 3,  6,  9],
       [12, 15, 18]])

In [105]:
np.array([[0],[10],[20]]) + np.array([1,2,3]) # 띠용?

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

# Comparisons
numpy 값들을 비교

In [106]:
a = np.arange(10)

In [107]:
np.any(a > 5)

True

In [109]:
np.any(a < 0) # Or조건이다.

False

In [113]:
np.all(a > 5)# and 조건이다

False

In [112]:
np.all(a < 10)

True

In [114]:
a = np.array([1,2,0], float)
b = np.array([5,1,1], float)
 
a > b # element-wise 하게 비교도 가능

array([False,  True, False])

In [115]:
a == b

array([False, False, False])

In [116]:
# 복합 조건들
a = np.array([1,3,0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [117]:
b = np.array([True, False, True])
np.logical_not(b)

array([False,  True, False])

## np.where

In [118]:
a = np.arange(10)
np.where(a > 5) # True, False 를 주지 않으면.. True 인 인덱스 반환

(array([6, 7, 8, 9]),)

In [119]:
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False])

In [120]:
np.where(a > 5, True, False)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [122]:
np.isfinite(a) # 실수 등의 유리수인가

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## argmax, argmin
최대 최소값의 인덱스 반환

In [123]:
a = np.arange(10)

In [124]:
np.argmax(a)

9

In [125]:
np.argmin(a)

0

In [129]:
a = np.random.normal(0,1,10).reshape(2,5)

In [130]:
np.argmax(a, axis=1)

array([2, 1])

In [131]:
np.argmin(a, axis=1)

array([1, 2])

# boolean & fancy index

In [132]:
a = np.array([1,4,0,2,3,8,9,7], float)

In [138]:
# boolean index
a[a > 5] # 조건이 true 인 인덱스의 element 만 추출

array([8., 9., 7.])

In [135]:
mask = a < 5

In [136]:
mask # 마스크를 사용 가능

array([ True,  True,  True,  True,  True, False, False, False])

In [137]:
a[mask]

array([1., 4., 0., 2., 3.])

## Fancy index

In [144]:
a = np.array([2,4,6,8])
b = np.array([0,0,1,2,2,1], int)

a[b] # numpy 배열을 index로 사용할 수 있음

array([2, 2, 4, 6, 6, 4])

In [145]:
a.take(b) # == a[b] 

array([2, 2, 4, 6, 6, 4])

In [146]:
a = np.array([[1,4],[9,16],[7,2]])
a[b] # row로 취급됨

array([[ 1,  4],
       [ 1,  4],
       [ 9, 16],
       [ 7,  2],
       [ 7,  2],
       [ 9, 16]])

## Numpy data I/O

In [147]:
# text 읽기
# a = np.loadtxt("")

In [149]:
# csv로 저장
# np.savetxt("파일명", 배일, 구분자=",")

In [151]:
# pickle 형태로 저장
# np.save("파일명", arr=[array])

In [152]:
# 파일 읽기
# np.load(file="파일명")